<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <gazebo reference="base_link">
        <material>Gazebo/Green</material>
    </gazebo>

    <gazebo reference="slider_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="arm_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo>
        <plugin name="gazebo_ros_joint_state_publisher"
            filename="libgazebo_ros_joint_state_publisher.so">
            <update_rate>20</update_rate>
            <joint_name>slider_joint</joint_name>
            <joint_name>arm_joint</joint_name>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin name="gazebo_ros_joint_pose_trajectory"
            filename="libgazebo_ros_joint_pose_trajectory.so">
            <update_rate>20</update_rate>
        </plugin>
    </gazebo>

    <joint name="camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-1.571 0 -1.571" />
        <parent link="camera_link" />
        <child link="camera_link_optical" />
    </joint>

    <link name="camera_link_optical"></link>

    <gazebo reference="camera_link">
        <sensor type="camera" name="my_camera">
            <update_rate>20</update_rate>
            <visualize>true</visualize>
            <camera name="cam">
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.02</near>
                    <far>300</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link_optical</frame_name>
            </plugin>
        </sensor>
    </gazebo>

    <link name="ir_link">
        <origin xyz="${arm_length} 0 ${arm_radius - 0.075}" rpy="0 0 0"/>
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="0.01 0.01 0.01"/>
          </geometry>
        </collision>    <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="0.01 0.01 0.01"/>
          </geometry>
          <material name="black">
            <color rgba="0 0 0 1"/>
        </material>
        </visual>
        <xacro:inertial_box mass="1e-5" x="0.01" y="0.01" z="0.01">
            <origin xyz="0.0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="ir_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 1.571 0"/>
        <parent link="arm_link"/>
        <child link="ir_link"/>
    </joint>

    <gazebo reference="ir_link">        
        <sensor type="ray" name="TeraRanger">
           <pose>0 0 0 0 0 0</pose>
           <visualize>true</visualize>
           <update_rate>50</update_rate>
           <ray>
              <scan>
                 <horizontal>
                    <samples>10</samples>
                    <resolution>1</resolution> 
                    <min_angle>-0.14835</min_angle>
                    <max_angle>0.14835</max_angle>
                 </horizontal>
                 <vertical>
                    <samples>10</samples>
                    <resolution>1</resolution> 
                    <min_angle>-0.14835</min_angle>
                    <max_angle>0.14835</max_angle> 
                 </vertical>
              </scan>
              <range>
                 <min>0.01</min>
                 <max>2</max>
                 <resolution>0.02</resolution>
              </range>
           </ray>
           <plugin filename="libgazebo_ros_ray_sensor.so" name="gazebo_ros_range">
              <gaussianNoise>0.005</gaussianNoise>
              <alwaysOn>true</alwaysOn>
              <updateRate>50</updateRate>
              <topicName>sensor/ir_front</topicName>
              <frameName>ir_link</frameName>
              <radiation>INFRARED</radiation>
              <fov>0.2967</fov>
           </plugin>
        </sensor>  
        </gazebo>
</robot>