controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController

effort_controller:
  ros__parameters:
    joints:
      - slider_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      
position_controller:
  ros__parameters:
    joints:
      - arm_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    